version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "63306:3306"
    volumes:
      - nekochans-serverless-api-mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
  migrate:
    build:
      context: .
      dockerfile: docker/migrate/Dockerfile
    restart: always
    command: 'tail -f /dev/null'
    environment:
      MIGRATION_DSN: ${MIGRATION_DSN}
      MIGRATION_TEST_DSN: ${MIGRATION_TEST_DSN}
    volumes:
      - ./:/go/app
      - exclude:/go/app/node_modules/
volumes:
  nekochans-serverless-api-mysql:
  exclude:
    driver: 'local'
