name: cd-development

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy To Development
    runs-on: ubuntu-latest
    env:
      DEPLOY_STAGE: dev
      AWS_PROFILE: nekochans-dev
      DB_WRITER_HOSTNAME: ${{ secrets.DB_WRITER_HOSTNAME }}
      DB_READER_HOSTNAME: ${{ secrets.DB_READER_HOSTNAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}
      SUBNET_ID_1: ${{ secrets.SUBNET_ID_1 }}
      SUBNET_ID_2: ${{ secrets.SUBNET_ID_2 }}
      SUBNET_ID_3: ${{ secrets.SUBNET_ID_3 }}
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Add profile credentials to ~/.aws/credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile $AWS_PROFILE
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile $AWS_PROFILE

      - name: Deploy to AWS
      - run: |
          npm ci
          npm run prisma:generate
          npm run deploy
